# Introdución a Numpy

In [6]:
import numpy as np

# Arrays
Es una estructura de datos 
un axis
un shape (3,5)
un size 15

In [7]:
# Array cuyos valores son todo 0
a=np.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 5)
15


describe el Array
2 axis

In [10]:
#ejemplo 2
a=np.zeros((2,3,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [11]:
print(a.ndim)
print(a.shape)
print(a.size)

3
(2, 3, 4)
24
